RfgUtil.exe .\1_map\ -c -e
RfgUtil.exe .\2_map\ -c -e
RfgUtil.exe .\3_map\ -c -e
RfgUtil.exe .\4_map\ -c -e
RfgUtil.exe .\5_map\ -c -e
RfgUtil.exe .\6_map\ -c -e
RfgUtil.exe .\7_map\ -c -e
RfgUtil.exe .\8_map\ -c -e
RfgUtil.exe .\9_map\ -c -e
RfgUtil.exe .\10_map\ -c -e
RfgUtil.exe .\11_map\ -c -e
RfgUtil.exe .\12_map\ -c -e
RfgUtil.exe .\13_map\ -c -e
RfgUtil.exe .\14_map\ -c -e
RfgUtil.exe .\15_map\ -c -e
RfgUtil.exe .\16_map\ -c -e
RfgUtil.exe .\17_map\ -c -e
RfgUtil.exe .\18_map\ -c -e
RfgUtil.exe .\19_map\ -c -e
RfgUtil.exe .\mp_test1_map\ -c -e
RfgUtil.exe .\mp_test2_map\ -c -e
RfgUtil.exe .\mp_test3_map\ -c -e
RfgUtil.exe .\mp_air_map\ -c -e
RfgUtil.exe .\mp_koth_map\ -c -e
RfgUtil.exe .\mp_koth2_map\ -c -e
RfgUtil.exe .\mp_crater_map\ -c -e