RfgUtil.exe .\dlc_eddie\ -c -e
RfgUtil.exe .\dlc_harvey\ -c -e
RfgUtil.exe .\dlc_john\ -c -e
RfgUtil.exe .\dlc_kat\ -c -e
RfgUtil.exe .\dlc_mis_assault_edf_marius\ -c -e
RfgUtil.exe .\dlc_mis_assault_edf_official\ -c -e
RfgUtil.exe .\dlc_dan\ -c -e
RfgUtil.exe .\dlc_mis_rfcommander\ -c -e
RfgUtil.exe .\dlc_muir\ -c -e
RfgUtil.exe .\dlc_pierce\ -c -e
RfgUtil.exe .\dlc_slade\ -c -e
RfgUtil.exe .\dlc_sam\ -c -e
RfgUtil.exe .\dlc_celia\ -c -e
RfgUtil.exe .\dlc_vasha\ -c -e
RfgUtil.exe .\dlc_hess\ -c -e