RfgUtil.exe .\vanilla_wcdlc1_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc2_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc3_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc4_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc5_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc6_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc7_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc8_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc9_map\ -c -e