RfgUtil.exe .\mp_junkyard_map\ -c -e
RfgUtil.exe .\mp_cliffside_map\ -c -e
RfgUtil.exe .\mp_partial_recall_map\ -c -e
RfgUtil.exe .\mp_shipment_map\ -c -e
RfgUtil.exe .\mp_townhall_map\ -c -e
RfgUtil.exe .\mp_warehouse_map\ -c -e
RfgUtil.exe .\mp_spire_map\ -c -e
RfgUtil.exe .\vanilla_wc1_map\ -c -e
RfgUtil.exe .\vanilla_wc2_map\ -c -e
RfgUtil.exe .\vanilla_wc3_map\ -c -e
RfgUtil.exe .\vanilla_wc4_map\ -c -e
RfgUtil.exe .\vanilla_wc5_map\ -c -e
RfgUtil.exe .\vanilla_wc6_map\ -c -e
RfgUtil.exe .\vanilla_wc7_map\ -c -e
RfgUtil.exe .\vanilla_wc8_map\ -c -e
RfgUtil.exe .\vanilla_wc9_map\ -c -e
RfgUtil.exe .\vanilla_wc10_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc1_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc2_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc3_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc4_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc5_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc6_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc7_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc8_map\ -c -e
RfgUtil.exe .\vanilla_wcdlc9_map\ -c -e